# .bashrc

# User specific aliases and functions

alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

history_control=ignoredups

alias cls='clear'
alias p='pwd'
alias w='which'
alias h='history'
alias vi='vim'

#For directory move
alias up='cd ..'
alias ..='cd ..'
alias up2='cd ../..'
alias up3='cd ../../..'
alias ga='grep -r -n "\!*" * |\grep -v Binary |\grep -v text-base |\grep -v .svn |\grep -v "\.o:" |\grep -v "\.d:" |\grep -v "\.a:" |\grep -v "\.swp:"'
alias s.b='source ~/.bashrc'
alias v.b='vim ~/.bashrc'
alias cdligm='cd /export/ligm/'
alias cdgit='cd /export/ligm/my_git_repo/'
alias ligm='vim /export/ligm/my_git_repo/linux_learning/learning.txt' 
alias share='nohup synergy >/dev/null 2>&1 &'
alias mountwin='mount -t cifs -o username=ligm,password=love661314 //10.72.125.239/share /mnt/share'

export TERM=xterm-256color

# For vim usage
alias tags='ctags -R .' 
if [ -f ~/.dir_colors/dircolors.256dark ]
then
    eval `dircolors ~/.dir_colors/dircolors.256dark`
fi


# For git usage
alias gst='git status' 
alias commit='git commit'
alias pushmaster='git push origin master'
alias log='git log'
alias pull='git pull --rebase'

# For shadowsocks
alias socks='nohup sslocal -c /etc/shadowsocks.json > /dev/null 2>&1&'

